#!/bin/bash
DEMO=demo

tarry() {
	stty -echo
	read -n1 JUNK
}

dally() {
	sleep 0.4
}

prompt() {
	echo -en "\033[1;32mjhunt@${DEMO}\033[0m \033[1;34m~\033[0m \033[1;33m→\033[0m "
}

save() {
	echo -en "\033[s"
}

restore() {
	echo -en "\033[u"
}

cmd() {
	save ; prompt ; tarry
	restore ; prompt ; echo "$@" ; dally
	restore ; prompt ; echo "$@" ; $@ ; echo
}

fake() {
	save ; prompt ; tarry
	restore ; prompt ; echo "$@" ; dally
}

fin() {
	clear; tarry
	echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo
	echo "                                                   fin"
	echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo
	tarry
	stty echo
}

title() {
	echo -ne "\033]0;$1\007"
}

clear
title BROKER
echo "loading vault demo..."
(cf set-target -f boston
 cf target -o jhunt -s vault-demo
 cf push -p ~/cf/cf-env -n env an-app) >/dev/null 2>&1

clear
fake cf target
(cf target -o jhunt -s vault-demo) >/dev/null 2>&1
cf target ; echo
cmd cf service-brokers
cmd cf marketplace

tarry; clear
cmd cf create-service vault shared demo-vault
cmd cf services

tarry; clear
cmd cf apps
cmd cf bind-service an-app demo-vault
fake cf env an-app
cf env an-app | head -n 34 | tail -n 30 | jq -r '{ "credentials": .VCAP_SERVICES.vault[0].credentials }'
(cf delete -f env
 cf delete-service -f demo-vault) >/dev/null 2>&1

tarry; fin
